export const LOAD_RESOURCE_START = 'LOAD_RESOURCE_START';
export const LOAD_RESOURCE_SUCCESS = 'LOAD_RESOURCE_SUCCESS';
export const LOAD_RESOURCE_FAIL = 'LOAD_RESOURCE_FAIL';
export const LOAD_USER_START = 'LOAD_USER_START';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';
export const INPUT_TEXT = 'INPUT_TEXT';
